apiVersion: v1
kind: Service
metadata:
  name: excluicontatoapi-service
spec:
  type: NodePort
  selector:
    app: excluicontatoapi
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30085 # Porta externa para acesso
