apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    # Coloque o conteúdo completo do arquivo prometheus.yml aqui
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"

        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.

        static_configs:
          - targets: ["prometheus-service"]

      - job_name: "Meus_Contatos"
        static_configs:
          - targets: ["webapp-service"]

      - job_name: "AlteraContatoAPI"
        static_configs:
          - targets: ["alteracontatoapi-service"]
  
      - job_name: "BuscaContatoAPI"
        static_configs:
          - targets: ["buscacontatoapi-service"]
  
      - job_name: "ExcluiContatoAPI"
        static_configs:
          - targets: ["excluicontatoapi-service"]
  
      - job_name: "AdicionaContatoAPI"
        static_configs:
          - targets: ["adicionarcontatoapi-service"]
  
      - job_name: "BuscaDDDApi"
        static_configs:
          - targets: ["buscadddapi-service"]

