apiVersion: v1
kind: Service
metadata:
  name: adicionarcontatoapi-service
spec:
  type: NodePort
  selector:
    app: adicionarcontatoapi
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081 # Porta externa para acesso
