apiVersion: v1
kind: Service
metadata:
  name: usuario-service
spec:
  type: NodePort
  selector:
    app: usuario
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30086 # Porta externa para acesso
