apiVersion: v1
kind: Service
metadata:
  name: alteracontatoapi-service
spec:
  type: NodePort
  selector:
    app: alteracontatoapi
  ports:
  - port: 80
    targetPort: 5004
    nodePort: 30082 # Porta externa para acesso
