apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscacontatoapi-deployment
  labels:
    app: buscacontatoapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buscacontatoapi
  template:
    metadata:
      labels:
        app: buscacontatoapi
    spec:
      containers:
      - name: buscacontatoapi
        image: trickfx/buscacontatoapi:latest
        ports:
        - containerPort: 8080
