apiVersion: apps/v1
kind: Deployment
metadata:
  name: adicionar-contato-deployment
  labels:
    app: adicionar-contato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adicionar-contato
  template:
    metadata:
      labels:
        app: adicionar-contato
    spec:
      containers:
      - name: adicionar-contato
        image: trickfx/adicionarcontatoapi:latest # Imagem Docker da API AdicionarContatoAPI
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altera-contato-deployment
  labels:
    app: altera-contato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: altera-contato
  template:
    metadata:
      labels:
        app: altera-contato
    spec:
      containers:
      - name: altera-contato
        image: trickfx/alteracontatoapi:latest # Imagem Docker da API AlteraContatoAPI
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busca-contato-deployment
  labels:
    app: busca-contato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busca-contato
  template:
    metadata:
      labels:
        app: busca-contato
    spec:
      containers:
      - name: busca-contato
        image: trickfx/buscacontatoapi:latest # Imagem Docker da API BuscaContatoAPI
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busca-ddd-deployment
  labels:
    app: busca-ddd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busca-ddd
  template:
    metadata:
      labels:
        app: busca-ddd
    spec:
      containers:
      - name: busca-ddd
        image: trickfx/buscadddapi:latest # Imagem Docker da API BuscaDddAPI
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exclui-contato-deployment
  labels:
    app: exclui-contato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exclui-contato
  template:
    metadata:
      labels:
        app: exclui-contato
    spec:
      containers:
      - name: exclui-contato
        image: trickfx/excluircontatoapi:latest # Imagem Docker da API ExcluiContatoAPI
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-deployment
  labels:
    app: usuario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuario
  template:
    metadata:
      labels:
        app: usuario
    spec:
      containers:
      - name: usuario
        image: trickfx/usuarioapi:latest # Imagem Docker da API UsuarioAPI
        ports:
        - containerPort: 80
