apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-config
data:
  datasources.yaml: |
    # Coloque o conteúdo do arquivo `datasources.yaml` aqui
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: grafana-service:30300
        isDefault: true
        editable: true
        uid: adt2ajoxutb7kd
