version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "M@sterk3y"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "usuariodb"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  meus_contatos:
    build:
      context: .
      dockerfile: Meus_Contatos/Dockerfile
    ports:
      - "8080:8080"
    image: trickfx/meuscontatos:latest
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"
      ASPNETCORE_URLS: "http://host.docker.internal:8080"

  usuariosAPI:
    build:
      context: ../API/UsuarioAPI/UsuariosAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=usuariodb;User=root;Password=root;"
      ASPNETCORE_URLS: "http://host.docker.internal:5000"

  buscacontatoapi:
    build:
      context: ../API/BuscaContatoAPI/BuscaContatoAPI/
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"
      ASPNETCORE_URLS: "http://host.docker.internal:5001"

  buscadddapi:
    build:
      context: ../API/BuscaDddAPI/
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"
      ASPNETCORE_URLS: "http://host.docker.internal:5002"
  
  adicionarcontatoapi:
    build:
      context: ../API/AdicionarContatoAPI/
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"
      ASPNETCORE_URLS: "http://host.docker.internal:5003"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../Prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ../Grafana/Provisioning:/etc/grafana/provisioning
      - ../Grafana/Dashboards:/var/lib/grafana/dashboards
  
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      -  "5672:5672"
      -  "15672:15672"

volumes:
  sqlserverdata:
  mysqldata:
