name: AdicionarContatoAPIPipe

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Instalando o SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Realizando a restauração de pacotes Nuget
        run: dotnet restore API/AdicionarContatoAPI/AdicionarContatoAPI.sln

      - name: Realizando o build da aplicação
        run: dotnet build API/AdicionarContatoAPI/AdicionarContatoAPI.sln

      - name: Publicando artefatos do build
        uses: actions/upload-artifact@v3
        with:
          name: BuildOutput
          path: '**/bin/Release/**/*'

  Testes_Unitarios_Integracao:
    runs-on: ubuntu-latest
    needs: Build

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "M@sterk3y"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0" 
          --health-interval 10s
          --health-timeout 10s
          --health-retries 3

    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Instalando o SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Baixando artefatos do build
        uses: actions/download-artifact@v3
        with:
          name: BuildOutput

      - name: Instalando a ferramenta dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Adicionando dotnet tools ao PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Instalando ferramentas de linha de comando do SQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_ENV

      - name: Verificando se o SQL Server está pronto
        run: |
          for i in {1..10}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "M@sterk3y" -Q "SELECT 1" && break
            sleep 5
          done

      - name: Aplicando a migration do Entity Framework
        run: dotnet ef database update --project WebApp/Infrastructure --connection "Server=localhost,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"

      - name: Populando o banco de dados com os estados do Brasil
        run: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "M@sterk3y" -d contatos -i WebApp/Infrastructure/Scripts/SQL/InsertEstados.sql

      - name: Populando o banco de dados com as regiões do Brasil
        run: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "M@sterk3y" -d contatos -i WebApp/Infrastructure/Scripts/SQL/InsertRegioes.sql

      - name: Populando o banco de dados com os DDDs
        run: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "M@sterk3y" -d contatos -i WebApp/Infrastructure/Scripts/SQL/InsertDDDs.sql

      - name: Executando testes unitários
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=contatos;User id=sa;Password=M@sterk3y;TrustServerCertificate=True"
        run: dotnet test ./build/API/AdicionarContatoAPI/AdicionarContatoAPITests/bin/Release/net8.0/AdicionarContatoAPITests.dll --no-build --configuration Release --logger:trx

      - name: Publicando resultados dos testes unitários
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/*.trx'
