name: AdicionarContatoPipe

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4

      - name: Instalando o SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Realizando a restauração de pacotes Nuget
        run: dotnet restore API/AdicionarContatoAPI/AdicionarContatoAPI.sln

      - name: Realizando o build da aplicação
        run: dotnet build API/AdicionarContatoAPI/AdicionarContatoAPI.sln --no-restore --configuration Release

      - name: Publicando artefatos do build
        uses: actions/upload-artifact@v3
        with:
          name: BuildOutput
          path: '**/bin/Release/**'

  Testes_Unitarios_Integracao:
    runs-on: ubuntu-latest
    needs: Build

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "M@sterk3y"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0" 
          --health-interval 10s
          --health-timeout 10s
          --health-retries 3

    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4

      - name: Instalando o SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Baixando artefatos do build
        uses: actions/download-artifact@v3
        with:
          name: BuildOutput
          path: './build'