name: WebAppPipe

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4

      - name: Instalando o SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Realizando a restauração de pacotes Nuget
        run: dotnet restore WebApp/Meus_Contatos.sln

      - name: Realizando o build da aplicação
        run: dotnet build WebApp/Meus_Contatos.sln --no-restore --configuration Release

  Build_Docker:
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Realizando o checkout do fonte
        uses: actions/checkout@v4

      - name: Inicializando o buildx do Docker
        uses: docker/setup-buildx-action@v1
        
      - name: Realizando o login no docker
        uses: docker/login-action@v3.2.0
        with:
          username: 'trickfx'
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Realizando o build e publicação da imagem
        uses: docker/build-push-action@v6.2.0
        with:
          context: WebApp/
          tags: trickfx/meus-contatos:latest
          push: true          

      - name: Finalizando a sessão do docker
        run: docker logout